#ifndef EXIT_NO_ERRORS
#define EXIT_NO_ERRORS 0
#define ERROR_ARG_COUNT 1
#define ERROR_FILENAME 2
#define ERROR_MAGICNUMBER 3
#define ERROR_COMMENT 4
#define ERROR_DIMENSIONS 5
#define ERROR_MAX_GRAY 6
#define ERROR_MALLOC_IMAGE 7
#define ERROR_DATA 8
#define ERROR_OUT 9
#define ERROR_LAYOUT 10
#define ECHOED 90
#define IDENTICAL 91
#define DIFFERENT 92
#define CONVERTED 93
#define REDUCED 94
#define TILED 95
#define ASSEMBLED 96
#define ERROR_MISC 100
#define ERROR_MISC_MALLOC 101
#define ERROR_MISC_SAME_FORMAT_R 102
#define ERROR_MISC_SAME_FORMAT_P 103
#define ERROR_MISC_SCALEFACTOR 104
#define ERROR_MISC_TILE_TEMPLATE 105
#define ERROR_MISC_ASSEMBLE_BOUNDS 106
#endif
